version: "3.9"

services:
  db:
    image: postgres:15-alpine
    container_name: neuro-resume-db
    environment:
      POSTGRES_DB: neuro_resume
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
    container_name: neuro-resume-backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@db:5432/neuro_resume
      JWT_SECRET: ${JWT_SECRET:-change_me}
      JWT_ALGORITHM: HS256
      JWT_EXPIRATION: 86400
      LOG_LEVEL: INFO
      CORS_ORIGINS: ${CORS_ORIGINS:-http://localhost:3000}
      APP_ENV: production
      DEBUG: "0"
      PORT: 8000
    ports:
      - "8000:8000"

volumes:
  db_data:
